### ISSUE TITLE
Feature Request: Support more than one instance

### ISSUE THREAD

**Issue by TheOceanBreeze** [Lartsch/FediAct#10] opened 2022-12-14 18:58 UTC
I would like to be able to use multiple accounts within this extension, seeing as I have more than one account on different instances.

**Comment by Lartsch** [comment] 2022-12-14 19:25
Duplicate of #7. Version v0.9.6.2 has added a check if you are logged when surfing another instance than your home instance and will not process the site if so.

Chrome Webstore releases take 1-2 days until approved. If you are a Chrome user, you can still use the manual installation to use the latest version.

**Closed by Lartsch** 2022-12-14 19:25 UTC
